# Generated by Django 4.0.2 on 2022-02-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='learn'),
            preserve_default=False,
        ),
    ]
