# Generated by Django 4.0.2 on 2022-02-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_author_profile_picture_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default='img', upload_to=''),
            preserve_default=False,
        ),
    ]
